# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: eric e albright
email:
description:
copyright: "&copy; 2016 eric e albright"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ericealbright.github.io" # the base hostname & protocol for your site

# External Usernames
twitter_username:   ericealbright
github_username:    ericealbright
instagram_username: ericealbright

# Build settings
markdown: kramdown

# Exclude
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', '_ignore']